# src/notifier.py
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.utils import formataddr
from typing import Optional
import os

class EmailNotifier:
    def __init__(self):
        # 优先从环境变量获取，如果没有则留空 (需要在 .env 或 GitHub Secrets 配置)
        self.smtp_server = os.getenv("SMTP_SERVER", "smtp.qq.com")
        self.smtp_port = int(os.getenv("SMTP_PORT", "465"))
        self.sender_email = os.getenv("SMTP_USER") # 您的邮箱
        self.password = os.getenv("SMTP_PASSWORD") # 您的授权码
        self.receiver_email = os.getenv("EMAIL_TO") # 接收简报的邮箱

    def send_daily_report(self, date_str: str, markdown_content: str):
        if not all([self.sender_email, self.password, self.receiver_email]):
            print("⚠️ [Notifier] 缺少邮件配置，跳过发送。")
            return

        print(f"📧 正在通过 {self.smtp_server} 发送邮件...")
        
        try:
            msg = MIMEMultipart()
            msg['From'] = formataddr(["News Saga Bot", self.sender_email])
            msg['To'] = self.receiver_email
            msg['Subject'] = f"📰 新闻简报 ({date_str}) - News Saga"

            # 简单的 Markdown 转 HTML 包装 (为了手机阅读体验)
            # 这里做一个最简转换，将换行符换成 <br>，保留基本可读性
            # 如果想更漂亮，可以引入 markdown2 库，但为了减少依赖，这里用纯文本展示
            html_content = f"""
            <html>
            <body>
                <pre style="font-family: sans-serif; white-space: pre-wrap;">
{markdown_content}
                </pre>
                <p style="color: gray; font-size: 12px;">Auto-generated by News Saga Engine</p>
            </body>
            </html>
            """
            
            msg.attach(MIMEText(html_content, 'html', 'utf-8'))

            with smtplib.SMTP_SSL(self.smtp_server, self.smtp_port) as server:
                server.login(self.sender_email, self.password)
                server.sendmail(self.sender_email, [self.receiver_email], msg.as_string())
            
            print("✅ 邮件发送成功!")

        except Exception as e:
            print(f"❌ 邮件发送失败: {e}")