# src/reporter.py
import os
import json
from pathlib import Path
from typing import List, Optional

# 引入数据结构
from .schema import DailyBriefing, NewsType, Saga, SagaStatus

class SagaReporter:
    def __init__(self, saga_db_dir: str = "data/sagas"):
        self.saga_db_dir = Path(saga_db_dir)
    
    def _load_all_sagas(self) -> List[Saga]:
        """从磁盘读取所有 Saga 状态文件"""
        sagas = []
        if not self.saga_db_dir.exists():
            return sagas
            
        for file_path in self.saga_db_dir.glob("*.json"):
            try:
                with open(file_path, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                    sagas.append(Saga(**data))
            except Exception as e:
                print(f"⚠️ 加载 Saga 失败 {file_path}: {e}")
        
        # 按最后更新时间倒序排列 (最近发生的在前面)
        sagas.sort(key=lambda x: x.last_updated, reverse=True)
        return sagas

    def _render_sagas_section(self, sagas: List[Saga]) -> str:
        """渲染 Story 区域 (智能叙事)"""
        if not sagas:
            return "*(暂无活跃的故事线)*"
            
        md_lines = ["## 📖 正在追踪的故事线 (Active Sagas)"]
        
        for saga in sagas:
            # 只显示活跃的，或者最近更新的
            if saga.status == SagaStatus.ARCHIVED:
                continue
                
            # 渲染单个卡片
            icon = "🔥" if saga.status == SagaStatus.ACTIVE else "💤"
            md_lines.append(f"### {icon} {saga.title}")
            md_lines.append(f"> **分类**: {saga.category} | **更新**: {saga.last_updated}")
            md_lines.append(f"")
            md_lines.append(f"{saga.context_summary}")
            md_lines.append(f"")
            
            # 渲染最新事件 (取最后3个)
            md_lines.append(f"**最新进展:**")
            for event in saga.events[-3:]: # 只显示最近3条
                stars = "⭐" * event.importance
                md_lines.append(f"- {event.date} {stars} **{event.title}**: {event.summary} [🔗]({event.source_url})")
            
            md_lines.append("---")
            
        return "\n".join(md_lines)

    def _render_daily_archive(self, briefing: Optional[DailyBriefing]) -> str:
        """
        [新增] 渲染今日全量档案 (折叠表格)
        """
        if not briefing:
            return ""
            
        items = briefing.news_items
        count = len(items)
        date = briefing.date
        
        md_lines = []
        md_lines.append(f"## 🗄️ 今日原始档案 ({date})")
        md_lines.append(f"共采集 {count} 条新闻。点击下方展开查看全量列表。")
        md_lines.append("")
        
        # 使用 HTML <details> 标签实现折叠
        md_lines.append(f"<details><summary><b>🖱️ 点击展开/收起今日全量新闻 ({count}条)</b></summary>")
        md_lines.append("")
        md_lines.append("| 类型 | 标题 | 来源 |")
        md_lines.append("| :--- | :--- | :--- |")
        
        for item in items:
            # 图标区分
            type_icon = "⚡" if item.type == NewsType.FLASH_SUB else "📺"
            type_text = "快讯" if item.type == NewsType.FLASH_SUB else "普通"
            
            # 标题处理 (如果是快讯，可能很长，截断一点? 暂时全显示)
            title = item.title.replace("|", "\|") # 转义表格符
            
            # 链接
            link = f"[Link]({item.url})"
            
            md_lines.append(f"| {type_icon} {type_text} | {title} | {link} |")
            
        md_lines.append("")
        md_lines.append("</details>")
        md_lines.append("")
        
        return "\n".join(md_lines)

    def generate_readme(self, file_path: str = "README.md", briefing: Optional[DailyBriefing] = None):
        """
        生成最终的 README 报告
        :param briefing: 当日的原始数据对象 (用于生成档案区)
        """
        print(f"📝 正在渲染报告: {file_path}...")
        
        # 1. 加载 Sagas
        sagas = self._load_all_sagas()
        
        # 2. 生成各部分内容
        header = f"# 🚀 News Saga Engine 每日简报"
        saga_section = self._render_sagas_section(sagas)
        archive_section = self._render_daily_archive(briefing) # 传入 raw data
        
        # 3. 组合
        full_content = f"""{header}

生成时间: {briefing.date if briefing else "Unknown"}

{saga_section}

{archive_section}

---
*Auto-generated by News Saga Engine v2.0*
"""
        
        # 4. 写入文件
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(full_content)
            
        print(f"✅ 报告生成完毕!")